# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    MaxArtifactSize: 1
  

- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'
   
- script: |
    npm install
    npm run build
    ls -la /home/einfochips/mypipe/_work/8/s/* .
    cp -r /home/einfochips/mypipe/_work/8/s/* .
  displayName: 'npm install and build'
- task: Npm@1
  inputs:
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: '974bcf44-2fa8-4468-943e-10a4c93d77e1/0405bf4d-ab33-4399-80c0-4d677ec5fd52'
