trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm cache clean --force
    npm install
  displayName: 'Clear npm cache and install dependencies'

- script: |
    echo "Adding missing fields to package.json"
    echo '{"name": "corona_app", "version": "0.1.0", "description": "Your project description", "repository": {"type": "git", "url": "https://github.com/bha1212002/project_corona_tracker"}, "license": "MIT"}' > package.json.tmp
    jq -s '.[0] * .[1]' package.json package.json.tmp > package.json
    rm package.json.tmp
  displayName: 'Update package.json'

- script: |
    npm install @babel/plugin-proposal-numeric-separator@latest
  displayName: 'Install specific version of @babel/plugin-proposal-numeric-separator'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Tagging the build
      $buildNumber = "$(Build.BuildNumber)"
      $tagName = "v$buildNumber" # Assuming you want to use the build number as the tag
      git tag $tagName
      git push origin $tagName
  displayName: 'Tagging build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    MaxArtifactSize: 1
